name: build

on:
  push:
    branches:
      - 2019
      - 2019-actions

jobs:
  build:
    runs-on: windows-2019

    steps:

    - name: Checkout iricdev-2019
      uses: actions/checkout@v2

    - name: Setup programs
      run: Copy-Item .\programs_std.prop .\programs.prop

    - name: Setup path for msbuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.9,17)'

    - name: Export HDF5 version
      run: |
        (Get-Content .\versions.cmd) | Foreach-Object {
          if ($_ -imatch '^set HDF5_VER=(?<version>.*)$') {
            $env:HDF5_VER = $Matches['version']
          }
        }
        Write-Output "HDF5_VER=$env:HDF5_VER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Cache hdf5
      id: cache-hdf5
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/lib/install/hdf5-${{env.HDF5_VER}}
        key: ${{runner.os}}-hdf5-${{hashFiles('./hdf5.*')}}

    - name: Build hdf5
      if: steps.cache-hdf5.outputs.cache-hit != 'true'
      run: msbuild /noLogo /maxCpuCount /target:hdf5-build iricdev.proj
