name: build

on:
  push:
    branches:
      - 2019-actions

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GENERATOR: Ninja Multi-Config
  SGEN: ninja-x64


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup path for msbuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.9,17)'

    - name: Export version numbers
      run: Get-Content .\versions.github_env | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Export version numbers with underscores
      run: |
        Write-Output "BOOST_UVER=$(($env:BOOST_VER).Replace(".", "_"))"      | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "EXPAT_UVER=$(($env:EXPAT_VER).Replace(".", "_"))"      | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Write-Output "OPENSSL_UVER=$(($env:OPENSSL_VER).Replace(".", "_"))"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        Copy-Item .\programs_std.prop .\programs.prop

    - name: debug
      run: |
        Write-Output "GENERATOR=$env:GENERATOR"
        Write-Output "SGEN=$env:SGEN"
        Get-Command msbuild
        msbuild -version
        Get-Command cmake
        cmake --version

    - name: Cache poco
      id: cache-poco
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/lib/install/poco-${{env.POCO_VER}}
        key: ${{runner.os}}-poco-${{hashFiles('./poco.*')}}

    - name: Build poco
      if: steps.cache-poco.outputs.cache-hit != 'true'
      run: msbuild /noLogo /maxCpuCount /target:poco-build iricdev.proj

